version: 1.2
workflows:
   -  name: hifiasmHic2meryl
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/hifiasmHicHaplotype2meryl.wdl
   -  name: assessT2Tcompletness
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/assessAsemblyCompletness.wdl
   -  name: findAssemblyBreakpoints
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/findAssemblyBreakpoints.wdl
