version: 1.2
workflows:
   -  name: hifiasmHic2meryl
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/hifiasmHicHaplotype2meryl.wdl
   -  name: evaluateHumanAssembly
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/evaluateHumanAssembly.wdl
   -  name: findAssemblyBreakpoints
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/findAssemblyBreakpoints.wdl
   -  name: longestReadsUpToCoverage
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/longestReadsUpToCoverage.wdl
      
      
      
