version: 1.2
workflows:
   -  name: hifiasmHic2meryl
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/hifiasmHicHaplotype2meryl.wdl
   -  name: evaluateHumanAssembly
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/evaluateHumanAssembly.wdl
   -  name: findAssemblyBreakpoints
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/findAssemblyBreakpoints.wdl
   -  name: longestReadsUpToCoverage
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/longestReadsUpToCoverage.wdl
   -  name: estimateTelomericLengths
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/estimate_telomeres.wdl  
   -  name: estimateTelomericLengthsLargeBam
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/estimate_telomeres.big_bam.wdl

      
      
      
